version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "reload/developers"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "reload/developers"
